name: best

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        shell: cmd
        run: |
          if exist loop.bat (
            cmd /c loop.bat
          ) else (
            echo "loop.bat not found, skipping..."
          )
